[package]
name = "spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
rspotify = { version = "0.13.3", features = ["env-file"] }
tokio = { version = "1.40.0", features = ["full"] }
dotenv = "0.15.0"
