[package]
name = "spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rspotify = { version = "0.13.3", features = ["env-file"] }
tokio = { version = "1.40.0", features = ["full"] }
